
package com.mycompany.princeheartclinic;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;


public class ReferralManagement extends javax.swing.JFrame {

    public ReferralManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        patientmodule = new javax.swing.JButton();
        medicalcondition = new javax.swing.JButton();
        familyhistory = new javax.swing.JButton();
        clinicteam = new javax.swing.JButton();
        riskassessment = new javax.swing.JButton();
        referralmanagement = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        riskassessmenttbl = new javax.swing.JTable();
        submitriskbtn = new javax.swing.JButton();
        viewrecords = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prince Heart Clinic");

        patientmodule.setText("PATIENT'S MODULE");
        patientmodule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientmoduleActionPerformed(evt);
            }
        });

        medicalcondition.setText("MEDICAL CONDITION");
        medicalcondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalconditionActionPerformed(evt);
            }
        });

        familyhistory.setText("FAMILY HISTORY");
        familyhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familyhistoryActionPerformed(evt);
            }
        });

        clinicteam.setText("CLINIC TEAM");
        clinicteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clinicteamActionPerformed(evt);
            }
        });

        riskassessment.setText("RISK ASSESSMENT");
        riskassessment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riskassessmentActionPerformed(evt);
            }
        });

        referralmanagement.setText("REFERRAL MANAGEMENT");
        referralmanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referralmanagementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(riskassessment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(clinicteam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(familyhistory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(patientmodule, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(medicalcondition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(referralmanagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(patientmodule)
                .addGap(60, 60, 60)
                .addComponent(medicalcondition)
                .addGap(60, 60, 60)
                .addComponent(familyhistory)
                .addGap(60, 60, 60)
                .addComponent(clinicteam)
                .addGap(60, 60, 60)
                .addComponent(riskassessment)
                .addGap(60, 60, 60)
                .addComponent(referralmanagement)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));

        jLabel1.setBackground(new java.awt.Color(102, 0, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REFERRAL MANAGEMENT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        riskassessmenttbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Id", "Age", "Gender", "Weight", "Height", "Lifestyle", "Blood Pressure Sytolic", "Blood Pressure Diastolic", "HeartRate", "Hypertension", "Cholesteral Level", "ECG Results", "RiskScore", "RiskCategory"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        riskassessmenttbl.setRowHeight(25);
        riskassessmenttbl.setSelectionBackground(new java.awt.Color(102, 0, 102));
        riskassessmenttbl.setShowGrid(true);
        riskassessmenttbl.setShowHorizontalLines(false);
        riskassessmenttbl.setShowVerticalLines(false);
        jScrollPane1.setViewportView(riskassessmenttbl);

        submitriskbtn.setBackground(new java.awt.Color(0, 153, 153));
        submitriskbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        submitriskbtn.setText("PRINT");
        submitriskbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitriskbtnActionPerformed(evt);
            }
        });

        viewrecords.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        viewrecords.setText("VIEW RECORDS");
        viewrecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewrecordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(submitriskbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(490, 490, 490)
                                .addComponent(viewrecords)))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewrecords)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(submitriskbtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientmoduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientmoduleActionPerformed
        Patients obj = new Patients();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_patientmoduleActionPerformed

    private void medicalconditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalconditionActionPerformed
         MedicalConditions obj = new MedicalConditions();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_medicalconditionActionPerformed

    private void familyhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familyhistoryActionPerformed
        FamilyHistory obj = new FamilyHistory();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_familyhistoryActionPerformed

    private void clinicteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clinicteamActionPerformed
        ClinicTeam obj = new ClinicTeam();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_clinicteamActionPerformed

    private void riskassessmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riskassessmentActionPerformed
        riskassessment obj = new riskassessment();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_riskassessmentActionPerformed

    private void referralmanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referralmanagementActionPerformed
        ReferralManagement obj = new ReferralManagement();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_referralmanagementActionPerformed

    private void viewrecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewrecordsActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clinicdb","root","");
            Statement st = con.createStatement();
            String sql = "Select * from     riskassessment";
            PreparedStatement ptst = con.prepareStatement(sql);
            ResultSet rs = ptst.executeQuery();
            DefaultTableModel tm = (DefaultTableModel)riskassessment.getModel();
            tm.setRowCount(0);
            while (rs.next()){
                Object o[] = {rs.getInt("PatientId"),
                    rs.getString("FirstName"),
                    rs.getString("SecondName"),
                    rs.getInt("Age"),
                    rs.getString("Gender"),
                    rs.getFloat("Weight"),
                    rs.getFloat("Height"),
                    rs.getString("Lifestyle"),
                    rs.getBigDecimal("BloodPressureSytolic"),
                    rs.getBigDecimal("BloodPressureDiastolic"),
                    rs.getInt("HeartRate"),
                    rs.getString("Hypertension"),
                    rs.getBigDecimal("CholesteralLevel"),
                    rs.getString("ECGResults"),
                    rs.getString("RiskScore"),
                    rs.getString("RiskCategory"),
                };
                tm.addRow(o);
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_viewrecordsActionPerformed

    private void submitriskbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitriskbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitriskbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReferralManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReferralManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReferralManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReferralManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReferralManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clinicteam;
    private javax.swing.JButton familyhistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton medicalcondition;
    private javax.swing.JButton patientmodule;
    private javax.swing.JButton referralmanagement;
    private javax.swing.JButton riskassessment;
    private javax.swing.JTable riskassessmenttbl;
    private javax.swing.JButton submitriskbtn;
    private javax.swing.JButton viewrecords;
    // End of variables declaration//GEN-END:variables
}
