
package com.mycompany.princeheartclinic;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.JCheckBox;


public class riskassessment extends javax.swing.JFrame {
 
    
      
    public riskassessment() {
      
        initComponents();
     
        smoking = new JCheckBox("smoking"); // Instantiate the smoking checkbox
        alcohol = new JCheckBox("alcohol"); // Instantiate the alcohol checkbox
        exercisefitness = new JCheckBox("exercisefitness"); // Instantiate the exercise/fitness checkbox
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        patientmodule = new javax.swing.JButton();
        medicalcondition = new javax.swing.JButton();
        familyhistory = new javax.swing.JButton();
        clinicteam = new javax.swing.JButton();
        riskassessment = new javax.swing.JButton();
        referralmanagement = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        patientid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        height = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        submitriskbtn = new javax.swing.JButton();
        medicalconditionLabel = new javax.swing.JLabel();
        bpsytolic = new javax.swing.JTextField();
        bpdiastolic = new javax.swing.JTextField();
        bpm = new javax.swing.JTextField();
        hypertension = new javax.swing.JComboBox<>();
        cholesterallevel = new javax.swing.JTextField();
        ecgresults = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        smoking = new javax.swing.JCheckBox();
        alcohol = new javax.swing.JCheckBox();
        exercisefitness = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prince Heart Clinic");

        patientmodule.setText("PATIENT'S MODULE");
        patientmodule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientmoduleActionPerformed(evt);
            }
        });

        medicalcondition.setText("MEDICAL CONDITION");
        medicalcondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalconditionActionPerformed(evt);
            }
        });

        familyhistory.setText("FAMILY HISTORY");
        familyhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familyhistoryActionPerformed(evt);
            }
        });

        clinicteam.setText("CLINIC TEAM");
        clinicteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clinicteamActionPerformed(evt);
            }
        });

        riskassessment.setText("RISK ASSESSMENT");
        riskassessment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riskassessmentActionPerformed(evt);
            }
        });

        referralmanagement.setText("REFERRAL MANAGEMENT");
        referralmanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referralmanagementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(riskassessment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(clinicteam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(familyhistory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(patientmodule, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(medicalcondition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addComponent(referralmanagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(patientmodule)
                    .addGap(60, 60, 60)
                    .addComponent(medicalcondition)
                    .addGap(60, 60, 60)
                    .addComponent(familyhistory)
                    .addGap(60, 60, 60)
                    .addComponent(clinicteam)
                    .addGap(60, 60, 60)
                    .addComponent(riskassessment)
                    .addGap(60, 60, 60)
                    .addComponent(referralmanagement)
                    .addContainerGap(112, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));

        jLabel1.setBackground(new java.awt.Color(102, 0, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RISK ASSESMENT FORM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(476, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(449, 449, 449))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText(" INSERT THE PATIENTID TO RETRIEVE DATA.");

        search.setBackground(new java.awt.Color(0, 255, 0));
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("PatientId");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Age");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Gender");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Weight");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Height");

        height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Lifestyle");

        submitriskbtn.setBackground(new java.awt.Color(0, 153, 153));
        submitriskbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        submitriskbtn.setText("SUBMIT");
        submitriskbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitriskbtnActionPerformed(evt);
            }
        });

        medicalconditionLabel.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        medicalconditionLabel.setText("MEDICAL CONDITIONS:");

        hypertension.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("BLOOD PRESSURE SYTOLIC");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("HYPERTENSION");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("BLOOD PRESSURE DIASTOLIC");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("CHOLESTERAL LEVEL (mgdl)");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("HEART RATE (bpm)");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("ECG RESULTS");

        smoking.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        smoking.setText("Smoking");

        alcohol.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        alcohol.setText("Alcohol");

        exercisefitness.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        exercisefitness.setText("Exercise Fitness");
        exercisefitness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exercisefitnessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(submitriskbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(261, 261, 261)
                                            .addComponent(search))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(weight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(gender, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(age, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(patientid, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(50, 50, 50)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(height, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(smoking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(alcohol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(exercisefitness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGap(50, 50, 50)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bpdiastolic)
                                        .addComponent(bpm)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(medicalconditionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bpsytolic)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ecgresults, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                        .addComponent(cholesterallevel)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(hypertension, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(search))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(patientid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(smoking)
                                .addGap(10, 10, 10)
                                .addComponent(alcohol)
                                .addGap(10, 10, 10)
                                .addComponent(exercisefitness))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(hypertension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(medicalconditionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(bpsytolic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cholesterallevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bpdiastolic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ecgresults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addComponent(submitriskbtn)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientmoduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientmoduleActionPerformed
        Patients obj = new Patients();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_patientmoduleActionPerformed

    private void medicalconditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalconditionActionPerformed
        MedicalConditions obj = new MedicalConditions();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_medicalconditionActionPerformed

    private void familyhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familyhistoryActionPerformed
        FamilyHistory obj = new FamilyHistory();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_familyhistoryActionPerformed

    private void clinicteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clinicteamActionPerformed
        ClinicTeam obj = new ClinicTeam();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_clinicteamActionPerformed

    private void riskassessmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riskassessmentActionPerformed
        riskassessment obj = new riskassessment();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_riskassessmentActionPerformed

    private void referralmanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referralmanagementActionPerformed
        ReferralManagement obj = new ReferralManagement();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_referralmanagementActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        int PatientId = Integer.parseInt(patientid.getText());
          try {
    // Query to fetch patient information
    String patientQuery = "SELECT * FROM patienttbl WHERE PatientId = ?";
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clinicdb","root","");

    PreparedStatement ptst = con.prepareStatement(patientQuery);
    ptst.setInt(1, PatientId);
    ResultSet patientRs = ptst.executeQuery();

    // Checking if patient information is found
    if (patientRs.next()) {
        // Displaying the patient information
        int ageValue = patientRs.getInt("Age");
        String genderValue = patientRs.getString("Gender");
        float weightValue = patientRs.getFloat("Weight");
        float heightValue = patientRs.getFloat("Height");
        String lifestyleData = patientRs.getString("Lifestyle");

        // Processing lifestyle choices
        boolean smokingValue = false;
        boolean alcoholValue = false;
        boolean exercisefitnessValue = false;
        if (lifestyleData != null) {
            String[] lifestyleChoices = lifestyleData.split(",");
            for (String choice : lifestyleChoices) {
                if (choice.trim().equalsIgnoreCase("Smoking")) {
                    smokingValue = true;
                } else if (choice.trim().equalsIgnoreCase("Alcohol")) {
                    alcoholValue = true;
                } else if (choice.trim().equalsIgnoreCase("ExerciseFitness")) {
                    exercisefitnessValue = true;
                }
            }
        }

        // Setting patient information to GUI components
        age.setText(String.valueOf(ageValue));
        gender.setText(genderValue);
        weight.setText(String.valueOf(weightValue));
        height.setText(String.valueOf(heightValue));
        smoking.setSelected(smokingValue);
        alcohol.setSelected(alcoholValue);
        exercisefitness.setSelected(exercisefitnessValue);
    } else {
        // Displaying a message if patient not found
        JOptionPane.showMessageDialog(null, "Patient not found.");
    }

    // Query to fetch medical condition details
    String medicalQuery = "SELECT * FROM medicalconditiontbl WHERE patientid = ?";
    PreparedStatement medicalStmt = con.prepareStatement(medicalQuery);
    medicalStmt.setInt(1, PatientId);
    ResultSet medicalRs = medicalStmt.executeQuery();

    // Checking if medical condition details are found
    if (medicalRs.next()) {
        // Displaying the medical condition information
        float bloodPressureSytolicValue = medicalRs.getFloat("BloodPressureSytolic");
        float bloodPressureDiastolicValue = medicalRs.getFloat("BloodPressureDiastolic");
        float heartRateValue = medicalRs.getFloat("HeartRate");
        boolean hypertensionValue = medicalRs.getBoolean("Hypertension");
        float cholesterolLevelValue = medicalRs.getFloat("CholesteralLevel");
        String ecgResultsValue = medicalRs.getString("ECGResults");

        // Setting medical condition information to GUI components
        bpsytolic.setText(String.valueOf(bloodPressureSytolicValue));
        bpdiastolic.setText(String.valueOf(bloodPressureDiastolicValue));
        bpm.setText(String.valueOf(heartRateValue));
        hypertension.setSelectedItem(hypertensionValue ? "Yes" : "No");
        cholesterallevel.setText(String.valueOf(cholesterolLevelValue));
        ecgresults.setText(ecgResultsValue);
    } else {
        // Displaying a message if medical condition details not found
        JOptionPane.showMessageDialog(null, "Medical condition details not found.");
    }
    
        } catch (SQLException e) {
    // Handle SQL exceptions
    e.printStackTrace();
        
         }

    }//GEN-LAST:event_searchActionPerformed

    private void heightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightActionPerformed

    private void exercisefitnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exercisefitnessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exercisefitnessActionPerformed

    private void submitriskbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitriskbtnActionPerformed
int ageValue = Integer.parseInt(age.getText());
    boolean smokingValue = smoking.isSelected();
    boolean alcoholValue = alcohol.isSelected();
    boolean exerciseFitnessValue = exercisefitness.isSelected();
    String selectedHypertension = (String) hypertension.getSelectedItem();
    boolean hypertensionValue = selectedHypertension.equals("Yes");
    float cholesterolLevelValue = Float.parseFloat(cholesterallevel.getText());
    float bloodPressureSystolicValue = Float.parseFloat(bpsytolic.getText());
    float bloodPressureDiastolicValue = Float.parseFloat(bpdiastolic.getText());
    float heartRateValue = Float.parseFloat(bpm.getText());

    // Risk score calculation and display...
    // Define weights for each factor
    final float AGE_WEIGHT = 0.3f;
    final float LIFESTYLE_WEIGHT = 0.4f;
    final float MEDICAL_CONDITION_WEIGHT = 0.3f;

    // Initialize variables to store calculated factors
    float ageFactor = 0;
    float lifestyleFactor = 0;
    float medicalConditionFactor = 0;

    // Age factor calculation
    // Example: Older age contributes to higher risk
    if (ageValue >= 50) {
        ageFactor = 0.5f;
    } else if (ageValue >= 40) {
        ageFactor = 0.3f;
    } else {
        ageFactor = 0.1f;
    }

    // Lifestyle factor calculation
    // Example: Smoking and alcohol consumption increase risk
    if (smokingValue) {
        lifestyleFactor += 0.2f;
    }
    if (alcoholValue) {
        lifestyleFactor += 0.1f;
    }
    if (exerciseFitnessValue) {
        lifestyleFactor -= 0.1f; // Exercise reduces risk
    }

    // Medical condition factor calculation
    // Example: High blood pressure, cholesterol, and heart rate increase risk
    if (hypertensionValue) {
        medicalConditionFactor += 0.2f;
    }
    if (cholesterolLevelValue >= 200) {
        medicalConditionFactor += 0.1f;
    }
    if (bloodPressureSystolicValue >= 140 || bloodPressureDiastolicValue >= 90) {
        medicalConditionFactor += 0.1f;
    }
    if (heartRateValue >= 100) {
        medicalConditionFactor += 0.1f;
    }

    // Calculate overall risk score
    float riskScore = (AGE_WEIGHT * ageFactor) + (LIFESTYLE_WEIGHT * lifestyleFactor) + (MEDICAL_CONDITION_WEIGHT * medicalConditionFactor);
    // Categorize the risk based on thresholds
    String riskCategory;
    if (riskScore >= 0.7) {
        riskCategory = "High";
    } else if (riskScore >= 0.4) {
        riskCategory = "Moderate";
    } else {
        riskCategory = "Low";
    }
    // Display risk score to the user
     JOptionPane.showMessageDialog(null, "Risk Score: " + riskScore + "\nRisk Category: " + riskCategory);
     


    }//GEN-LAST:event_submitriskbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(riskassessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(riskassessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(riskassessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(riskassessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new riskassessment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JCheckBox alcohol;
    private javax.swing.JTextField bpdiastolic;
    private javax.swing.JTextField bpm;
    private javax.swing.JTextField bpsytolic;
    private javax.swing.JTextField cholesterallevel;
    private javax.swing.JButton clinicteam;
    private javax.swing.JTextField ecgresults;
    private javax.swing.JCheckBox exercisefitness;
    private javax.swing.JButton familyhistory;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField height;
    private javax.swing.JComboBox<String> hypertension;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton medicalcondition;
    private javax.swing.JLabel medicalconditionLabel;
    private javax.swing.JTextField patientid;
    private javax.swing.JButton patientmodule;
    private javax.swing.JButton referralmanagement;
    private javax.swing.JButton riskassessment;
    private javax.swing.JButton search;
    private javax.swing.JCheckBox smoking;
    private javax.swing.JButton submitriskbtn;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
