
package com.mycompany.princeheartclinic;


public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        patientsBtn = new javax.swing.JButton();
        medicalconditionBtn = new javax.swing.JButton();
        familyhistoryBtn = new javax.swing.JButton();
        clinicteamBtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        riskassessmentBtn = new javax.swing.JButton();
        referralmanagementBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("PRINCE HEART CLINIC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        patientsBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        patientsBtn.setText("Patients");
        patientsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientsBtnActionPerformed(evt);
            }
        });

        medicalconditionBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        medicalconditionBtn.setText("Medical Conditions");
        medicalconditionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalconditionBtnActionPerformed(evt);
            }
        });

        familyhistoryBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        familyhistoryBtn.setText("Family History");
        familyhistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familyhistoryBtnActionPerformed(evt);
            }
        });

        clinicteamBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        clinicteamBtn.setText("Clinic Team");
        clinicteamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clinicteamBtnActionPerformed(evt);
            }
        });

        logoutbtn.setBackground(new java.awt.Color(204, 204, 204));
        logoutbtn.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        logoutbtn.setText("LOG OUT");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        riskassessmentBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        riskassessmentBtn.setText("RiskAssessment");
        riskassessmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riskassessmentBtnActionPerformed(evt);
            }
        });

        referralmanagementBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        referralmanagementBtn.setText("Referral Management");
        referralmanagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referralmanagementBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutbtn)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(riskassessmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clinicteamBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(medicalconditionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(patientsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(familyhistoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(referralmanagementBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(patientsBtn)
                .addGap(10, 10, 10)
                .addComponent(medicalconditionBtn)
                .addGap(10, 10, 10)
                .addComponent(familyhistoryBtn)
                .addGap(10, 10, 10)
                .addComponent(clinicteamBtn)
                .addGap(10, 10, 10)
                .addComponent(riskassessmentBtn)
                .addGap(10, 10, 10)
                .addComponent(referralmanagementBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(logoutbtn)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
          new Login().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void patientsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientsBtnActionPerformed
        // TODO add your handling code here:
         Patients obj = new Patients();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_patientsBtnActionPerformed

    private void medicalconditionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalconditionBtnActionPerformed
       MedicalConditions obj = new MedicalConditions();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_medicalconditionBtnActionPerformed

    private void familyhistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familyhistoryBtnActionPerformed
          FamilyHistory obj = new FamilyHistory();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_familyhistoryBtnActionPerformed

    private void clinicteamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clinicteamBtnActionPerformed
          ClinicTeam obj = new ClinicTeam();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_clinicteamBtnActionPerformed

    private void riskassessmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riskassessmentBtnActionPerformed
        riskassessment obj = new riskassessment();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_riskassessmentBtnActionPerformed

    private void referralmanagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referralmanagementBtnActionPerformed
       ReferralManagement obj = new ReferralManagement();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_referralmanagementBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clinicteamBtn;
    private javax.swing.JButton familyhistoryBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton medicalconditionBtn;
    private javax.swing.JButton patientsBtn;
    private javax.swing.JButton referralmanagementBtn;
    private javax.swing.JButton riskassessmentBtn;
    // End of variables declaration//GEN-END:variables
}
